-- warehause

CREATE TABLE IF NOT EXISTS rack (
    rack_id int GENERATED BY DEFAULT AS IDENTITY,
    rack_number varchar(50) NOT NULL,

    PRIMARY KEY (rack_id)
);

CREATE TABLE IF NOT EXISTS shelf (
    shelf_id int GENERATED BY DEFAULT AS IDENTITY,
    shelf_number varchar(50) NOT NULL,
    rack_id int NOT NULL,

    PRIMARY KEY (shelf_id),
    CONSTRAINT fk_rack
        FOREIGN KEY (rack_id)
	    REFERENCES rack(rack_id)
);

CREATE TABLE IF NOT EXISTS cell (
    cell_id int GENERATED BY DEFAULT AS IDENTITY,
    cell_number varchar(50) NOT NULL,
    shelf_id int NOT NULL,

    PRIMARY KEY (cell_id),
    CONSTRAINT fk_shelf
        FOREIGN KEY (shelf_id)
	    REFERENCES shelf(shelf_id)
);

-- documents

CREATE TABLE IF NOT EXISTS document_subject (
    document_subject_id int GENERATED BY DEFAULT AS IDENTITY,
    document_subject_name varchar(255) NOT NULL,

    PRIMARY KEY (document_subject_id)
);

CREATE TABLE IF NOT EXISTS document (
    document_id int GENERATED BY DEFAULT AS IDENTITY,
    document_name varchar(255) NOT NULL,
    inventory_number varchar(50) NOT NULL,
    arrived_at timestamptz NOT NULL,
    cell_id int NOT NULL,
    document_subject_id int NOT NULL,

    PRIMARY KEY (document_id),
    CONSTRAINT fk_cell
        FOREIGN KEY (cell_id)
        REFERENCES cell(cell_id),
    CONSTRAINT fk_document_subject
        FOREIGN KEY (document_subject_id)
        REFERENCES document_subject(document_subject_id)
);

CREATE TABLE IF NOT EXISTS document_copy (
    copy_id int GENERATED BY DEFAULT AS IDENTITY,
    copy_name varchar(255) NOT NULL,
    inventory_number varchar(50) NOT NULL,
    document_id int NOT NULL,

    PRIMARY KEY(copy_id),
    CONSTRAINT fk_document
        FOREIGN KEY (document_id)
        REFERENCES document(document_id)
);

-- subscribers

CREATE TABLE IF NOT EXISTS department (
    department_id int GENERATED BY DEFAULT AS IDENTITY,
    phone_number varchar(255) NOT NULL,

    PRIMARY KEY (department_id)
);

CREATE TABLE IF NOT EXISTS subscriber (
    subscriber_id int GENERATED BY DEFAULT AS IDENTITY,
    first_name varchar(255) NOT NULL,
    last_name varchar(255) NOT NULL,
    middle_name varchar(255) NOT NULL,
    subscriber_number varchar(50) NOT NULL,
    department_id int NOT NULL,

    PRIMARY KEY (subscriber_id),
    CONSTRAINT fk_department
        FOREIGN KEY (department_id)
        REFERENCES department(department_id)
);

-- issues

CREATE TABLE IF NOT EXISTS document_issue (
    issue_id int GENERATED BY DEFAULT AS IDENTITY,
    issued_at timestamptz NOT NULL,
    returned_at timestamptz,
    subscriber_id int NOT NULL,
    document_id int NOT NULL,

    PRIMARY KEY (issue_id),
    CONSTRAINT fk_subscriber
        FOREIGN KEY (subscriber_id)
        REFERENCES subscriber(subscriber_id),
    CONSTRAINT fk_document
        FOREIGN KEY (document_id)
        REFERENCES document(document_id)
);

-- OPERATORS

CREATE TABLE IF NOT EXISTS operator (
    operator_id int GENERATED BY DEFAULT AS IDENTITY,
    operator_name varchar(255) NOT NULL,
    operator_password varchar(255) NOT NULL,

    PRIMARY KEY (operator_id)
);
