services:
    database:
        container_name: wms_database
        image: postgres
        restart: always
        env_file: ./.env
        # volumes:
        #     - ./db-init/init.sql:/docker-entrypoint-initdb.d/1.sql
        #     - ./db-init/fill.sql:/docker-entrypoint-initdb.d/2.sql
        #     - ./db-init/fill-issues.sql:/docker-entrypoint-initdb.d/3.sql
    server:
        container_name: wms_server
        build:
            context: ./server
        restart: always
        env_file: ./.env
        depends_on:
            - database
        environment:
            - NODE_ENV=production
            - POSTGRES_HOST=database
        ports:
            - '3000:3000'
    client:
        container_name: wms_client
        build: ./client
        restart: always
        depends_on:
            - server
        environment:
            - NODE_ENV=production
        ports:
            - '80:80'
